language: android

android:
  components:
    - tools
    - build-tools-28.0.0
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support

jdk:
  - oraclejdk8

notifications:
    email:
        - helloyako@gmail.com

cache: false
sudo: false

script:
  - chmod +x ./gradlew

