language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - build-tools-28.0.0
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support

notifications:
    email:
        - helloyako@gmail.com

cache: false
sudo: false

install:
    # Ensure Gradle wrapper is executable, download wrapper and show version
    - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
    
    # Download and show android dependencies
    - ./gradlew androidDependencies
    
script:
    - chmod +x ./gradlew

    - ./gradlew imagecropview:check imagecropview:assemble

